-- Tools that should be installed by Mason
-- LSPs that should be installed by Mason-lspconfig
return {
  lsp_servers = {
    "cssls",
    "html",
    "bashls",
    "dockerls",
    "jsonls",
    "helm_ls",
    "yamlls",
    "ansiblels",
    "gopls",
    "pyright",
    "lua_ls",
    "rust_analyzer",
    "clangd",
  },

  formatters = {
    go = { "goimports", "gofmt" },
    rust = { "rustfmt" },
    javascript = { "prettier" },
    json = { "prettier" },
    lua = { "stylua" },
    markdown = { "prettier" },
    python = { "isort", "ruff_format", "black" },
    sh = { "shfmt" },
    yaml = { "yamlfmt" },
    rst = { "rstfmt" },
  },

  linters = {
    dockerfile = { "hadolint" },
    go = { "revive", "golangcilint" },
    lua = { "selene" },
    sh = { "shellcheck" },
    yaml = { "yamllint" },
    puppet = { "puppet-lint" },
    python = { "pylint", "pydocstyle", "pycodestyle" },
    markdown = { "write_good", "markdownlint" },
    rst = { "rstcheck" },
  },

  treesitter = {
    "bash",
    "cmake",
    "css",
    "dockerfile",
    "go",
    "hcl",
    "html",
    "javascript",
    "json",
    "jsonc",
    "lua",
    "markdown",
    "markdown_inline",
    "query",
    "python",
    "regex",
    "toml",
    "vim",
    "yaml",
  },

  debuggers = {
    "python",
    "delve",
    "cppdbg",
    "bash",
    "codelldb",
  },
}
