-- Tools that should be installed by Mason
-- LSPs that should be installed by Mason-lspconfig
return {
  lsp_servers = {
    "cssls",
    "html",
    "bashls",
    "dockerls",
    "jsonls",
    "helm_ls",
    "yamlls",
    "ansiblels",
    "gopls",
    "pyright",
    "lua_ls",
    "rust_analyzer",
    "clangd",
    "ruby_lsp",
  },

  formatters = {
    c = { "clang-format" },
    cpp = { "clang-format" },
    go = { "goimports", "gofumpt" },
    javascript = { "prettier" },
    json = { "prettier" },
    lua = { "stylua" },
    markdown = { "prettier" },
    python = { "isort", "ruff", "black" },
    ruby = { "rubocop" },
    sh = { "shfmt" },
    yaml = { "yamlfmt" },
  },

  linters = {
    dockerfile = { "hadolint" },
    -- go = { "revive", "golangci-lint" },
    go = { "revive" },
    lua = { "selene" },
    sh = { "shellcheck" },
    yaml = { "yamllint" },
    python = { "pylint" },
    ruby = { "rubocop" },
    markdown = { "markdownlint-cli2" },
    rst = { "rstcheck" },
  },

  treesitter = {
    "bash",
    "c",
    "cmake",
    "cpp",
    "css",
    "dockerfile",
    "go",
    "hcl",
    "html",
    "javascript",
    "json",
    "jsonc",
    "lua",
    "markdown",
    "markdown_inline",
    "query",
    "python",
    "regex",
    "ruby",
    "rust",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vim",
    "yaml",
  },

  debuggers = {
    "debugpy",
    "delve",
    "bash-debug-adapter",
    "codelldb",
  },
}
