require("which-key").register({
    ["<leader>bb"] = { "<cmd>BufferLinePick<cr>", "Jump" },
    ["<leader>bf"] = { "<cmd>Telescope buffers<cr>", "Find" },
    ["<leader>bd"] = { function() require("spuxy.bufferline").buf_kill("bd", 0, false) end, "Delete buffer" },
    ["<leader>bj"] = { "<cmd>BufferLineCyclePrev<cr>", "Previous" },
    ["<leader>bk"] = { "<cmd>BufferLineCycleNext<cr>", "Next" },
    ["<leader>bp"] = { "<cmd>BufferLineTogglePin<cr>", "Pin" },
    ["<leader>bP"] = { "<cmd>BufferLineGroupClose ungrouped<cr>", "Delete non-pinned buffers" },
    ["<leader>be"] = { "<cmd>BufferLinePickClose<cr>", "Pick which buffer to close" },
    ["<leader>bo"] = { "<cmd>BufferLineCloseOthers<cr>", "Close others" },
    ["<leader>bl"] = { "<cmd>BufferLineCloseLeft<cr>", "Close all to the left" },
    ["<leader>br"] = { "<cmd>BufferLineCloseRight<cr>", "Close all to the right" },
    ["<leader>bW"] = { "<cmd>noautocmd w<cr>", "Save without formatting (noautocmd)" },
    ["<leader>bD"] = { "<cmd>BufferLineSortByDirectory<cr>", "Sort by directory" },
    ["<leader>bL"] = { "<cmd>BufferLineSortByExtension<cr>", "Sort by language" },
})